### ISSUE TITLE
JS and wasm targets

### ISSUE THREAD

**Issue by CaelumF** [oleksandrbalan/minabox#13]
Are there any plans for JS or WASM targets? I have a use case for js, and wasm some time down the line.

Based on my limited experience, it is only some scroll interaction code that needs to be separate between these platforms.

Any anticipation for how hard it would be?

**Comment by oleksandrbalan** [comment]
It is very interesting idea, but I have nearly no expirience with JS and WASM 🤷 

MinaBox already has desktop target, but with the same scrolling as Android or iOS. Do you want it to use mouse wheel button for vertical scroll on JS / WASM? Or "drag" is enough?

**Comment by oleksandrbalan** [comment]
It is very interesting idea, but I have nearly no expirience with JS and WASM 🤷 

MinaBox already has desktop target, but with the same scrolling as Android or iOS. Do you want it to use mouse wheel button for vertical scroll on JS / WASM? Or "drag" is enough?

**Comment by oleksandrbalan** [comment]
Thanks to @trueddd MinaBox can be lazy in the browser! 😸 

Check [1.7.0](https://github.com/oleksandrbalan/minabox/releases/tag/v1.7.0) release 🚀 

https://github.com/oleksandrbalan/minabox/assets/20944869/4ae3d987-7854-4dd2-9895-273f5ae8c6f4
