### ISSUE TITLE
Does it support Remote Control?

### ISSUE THREAD

**Issue by oxyroid** [oleksandrbalan/minabox#22]
Liking compose-tv artifact, more adaptations for tv. Such as scroll, item scaling, long pressed, etc.

**Comment by sbenmeddour** [comment]
You have to use `BringIntoViewResponder` & `BringIntoViewRequester` to have working scroll on focus
Long click & clicks are not related to the library, use tv-material with `Surface` & `Card` or you can even make your own `Modifier`

If the repo's owner read this, plead add the ability to set our own animationSpec for scroll ;)

**Comment by oxyroid** [comment]
@sbenmeddour Can you give me a bringIntoView sample for item scrolling?
